version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: "${MYSQL_USER}"
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3309:3306
  